#!/bin/bash
awk '
/const team = \[/ {
print "function AppSection() {"
print "  return ("
print "    <section className=\"py-24 md:py-48 px-6 md:px-12 bg-[#000] relative overflow-hidden\">"
print "      <div className=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-accent/5 rounded-full blur-[150px] pointer-events-none\" />"
print "      <div className=\"max-w-[1600px] mx-auto w-full relative z-10 flex flex-col items-center\">"
print "        <span className=\"text-accent text-[10px] uppercase tracking-[0.3em] font-bold block mb-8 text-center\">Tudo em um único lugar</span>"
print "        <RevealText>"
print "          <h2 className=\"text-5xl md:text-7xl lg:text-[6rem] font-display tracking-wide uppercase mb-10 max-w-5xl mx-auto text-center leading-[0.9]\">"
print "            Seu tratamento na <span className=\"text-accent\">palma da mão.</span>"
print "          </h2>"
print "        </RevealText>"
print "        <RevealText delay={0.1}>"
print "          <p className=\"text-lg md:text-xl text-text-secondary max-w-2xl mx-auto font-light leading-relaxed mb-24 text-center\">"
print "            Acompanhe suas receitas, agende teleconsultas com nossos especialistas e receba suporte jurídico diretamente pelo app exclusivo do Instituto Mecura."
print "          </p>"
print "        </RevealText>"
print "        <div className=\"relative w-full max-w-6xl mx-auto h-[650px] flex justify-center items-center mt-10\">"
print "            {/* LEFT PHONE (Chat) */}"
print "            <motion.div"
print "              initial={{ opacity: 0, x: -50, rotate: -12 }}"
print "              whileInView={{ opacity: 0.5, x: 0, rotate: -12 }}"
print "              viewport={{ once: true, margin: \"-10%\" }}"
print "              transition={{ duration: 1, ease: \"easeOut\" }}"
print "              className=\"absolute z-10 -ml-[400px] lg:-ml-[600px] scale-75 md:scale-90 hidden md:flex flex-col w-[300px] h-[620px] bg-[#0a0a0a] rounded-[3rem] border-[8px] border-[#1a1a1a] overflow-hidden shadow-2xl\""
print "            >"
print "              <div className=\"absolute top-0 inset-x-0 h-6 flex justify-center z-20\">"
print "                <div className=\"w-32 h-full bg-[#1a1a1a] rounded-b-2xl\"></div>"
print "              </div>"
print "              <div className=\"absolute top-16 -left-12 flex items-center gap-3 bg-[#111]/90 backdrop-blur-xl border border-white/10 p-3 pr-6 rounded-2xl shadow-2xl z-40 min-w-[240px]\">"
print "                <div className=\"w-10 h-10 rounded-full bg-[#1a1a1a] border border-border flex items-center justify-center shrink-0\">"
print "                   <MessageCircle className=\"w-4 h-4 text-accent\" />"
print "                </div>"
print "                <div className=\"flex flex-col items-start\">"
print "                   <div className=\"text-sm font-bold text-white leading-tight\">Nova Mensagem</div>"
print "                   <div className=\"text-[10px] text-text-secondary mt-0.5\">Dr. Guilherme: \"Tudo certo...\"</div>"
print "                </div>"
print "              </div>"
print "              <div className=\"p-6 pt-16 flex flex-col h-full bg-[#050505]\">"
print "                <div className=\"flex items-center gap-4 mb-8\">"
print "                  <img src=\"/dr-guilherme.png\" alt=\"Dr. Guilherme\" className=\"w-12 h-12 rounded-full object-cover border border-border\" />"
print "                  <div>"
print "                    <div className=\"font-bold text-sm text-white\">Dr. Guilherme Taveira</div>"
print "                    <div className=\"text-[10px] text-text-muted mt-1\">CRM 123456</div>"
print "                  </div>"
print "                </div>"
print "                <div className=\"flex flex-col gap-5 text-[13px]\">"
print "                  <div className=\"bg-[#111] p-4 rounded-2xl rounded-tl-sm w-[90%] text-text-secondary leading-relaxed border border-white/5\">"
print "                    Olá! Sou o Dr. Guilherme e vou fazer o seu atendimento hoje."
print "                  </div>"
print "                  <div className=\"bg-[#111] p-4 rounded-2xl rounded-tl-sm w-[95%] text-text-secondary leading-relaxed border border-white/5\">"
print "                    Acabei de ler as informações do seu prontuário. Tem algum ponto que queira reforçar?"
print "                  </div>"
print "                </div>"
print "                <div className=\"mt-auto relative\">"
print "                  <div className=\"w-full h-12 bg-[#111] border border-white/5 rounded-full flex items-center px-5 text-text-muted text-xs\">Escreva sua mensagem...</div>"
print "                  <div className=\"absolute right-1.5 top-1.5 w-9 h-9 bg-accent rounded-full flex items-center justify-center\">"
print "                     <Mic className=\"w-4 h-4 text-black\" />"
print "                  </div>"
print "                </div>"
print "              </div>"
print "            </motion.div>"
print "            {/* RIGHT PHONE (Checklist) */}"
print "            <motion.div"
print "              initial={{ opacity: 0, x: 50, rotate: 12 }}"
print "              whileInView={{ opacity: 0.5, x: 0, rotate: 12 }}"
print "              viewport={{ once: true, margin: \"-10%\" }}"
print "              transition={{ duration: 1, ease: \"easeOut\" }}"
print "              className=\"absolute z-10 ml-[400px] lg:ml-[600px] scale-75 md:scale-90 hidden md:flex flex-col w-[300px] h-[620px] bg-[#0a0a0a] rounded-[3rem] border-[8px] border-[#1a1a1a] overflow-hidden shadow-2xl\""
print "            >"
print "              <div className=\"absolute top-0 inset-x-0 h-6 flex justify-center z-20\">"
print "                <div className=\"w-32 h-full bg-[#1a1a1a] rounded-b-2xl\"></div>"
print "              </div>"
print "              <div className=\"absolute bottom-24 -left-16 flex items-center gap-3 bg-[#111]/90 backdrop-blur-xl border border-white/10 p-3 pr-6 rounded-2xl shadow-2xl z-40 min-w-[240px]\">"
print "                <div className=\"w-10 h-10 rounded-full bg-accent/10 border border-accent/20 flex items-center justify-center shrink-0\">"
print "                   <CheckCircle2 className=\"w-4 h-4 text-accent\" />"
print "                </div>"
print "                <div className=\"flex flex-col items-start\">"
print "                   <div className=\"text-sm font-bold text-white leading-tight\">Análise Concluída</div>"
print "                   <div className=\"text-[10px] text-text-secondary mt-0.5\">Perfil atualizado com sucesso</div>"
print "                </div>"
print "              </div>"
print "              <div className=\"p-6 pt-16 flex flex-col h-full bg-[#050505]\">"
print "                <h3 className=\"font-display text-2xl uppercase tracking-wide mb-2 text-white\">Estado Emocional</h3>"
print "                <p className=\"text-[10px] text-accent uppercase tracking-[0.2em] font-bold mb-8\">(1) Responda com atenção</p>"
print "                <div className=\"flex flex-col gap-6\">"
print "                  {["
print "                    \"Sente muita tristeza?\","
print "                    \"Perde o foco facilmente?\","
print "                    \"Tem problemas de memória?\","
print "                    \"Fica facilmente irritado?\","
print "                    \"Problemas com stress?\""
print "                  ].map((q, idx) => ("
print "                    <div key={idx} className=\"flex items-center justify-between border-b border-border/40 pb-4\">"
print "                       <span className=\"text-xs text-text-secondary leading-tight max-w-[70%]\">{q}</span>"
print "                       <div className=\"w-10 h-5 bg-[#222] rounded-full relative shadow-inner\">"
print "                         <div className=\"w-4 h-4 bg-[#555] rounded-full absolute top-0.5 left-0.5 transition-all\"></div>"
print "                       </div>"
print "                    </div>"
print "                  ))}"
print "                </div>"
print "                <button className=\"w-full py-4 bg-[#111] border border-white/5 text-text-primary font-bold uppercase tracking-[0.2em] rounded-full text-[10px] mt-auto hover:bg-[#1a1a1a] transition-colors\">"
print "                  Finalizar Análise"
print "                </button>"
print "              </div>"
print "            </motion.div>"
print "            {/* CENTER PHONE (Dashboard) */}"
print "            <motion.div"
print "              initial={{ opacity: 0, y: 50 }}"
print "              whileInView={{ opacity: 1, y: 0 }}"
print "              viewport={{ once: true, margin: \"-10%\" }}"
print "              transition={{ duration: 0.8, ease: \"easeOut\", delay: 0.2 }}"
print "              className=\"relative z-30 scale-100 md:scale-105 flex flex-col w-[320px] h-[650px] bg-[#0a0a0a] rounded-[3rem] border-[8px] border-[#1a1a1a] overflow-hidden shadow-[0_0_80px_rgba(0,0,0,0.8)]\""
print "            >"
print "              <div className=\"absolute top-0 inset-x-0 h-6 flex justify-center z-20\">"
print "                <div className=\"w-32 h-full bg-[#1a1a1a] rounded-b-2xl\"></div>"
print "              </div>"
print "              <div className=\"absolute top-48 -right-8 md:-right-24 flex items-center gap-3 bg-[#111]/90 backdrop-blur-xl border border-white/10 p-3 pr-6 rounded-2xl shadow-2xl z-40 min-w-[240px] transform md:hover:scale-105 transition-transform cursor-pointer\">"
print "                <div className=\"w-10 h-10 rounded-full bg-[#1a1a1a] border border-border flex items-center justify-center shrink-0\">"
print "                   <FileText className=\"w-4 h-4 text-accent\" />"
print "                </div>"
print "                <div className=\"flex flex-col items-start\">"
print "                   <div className=\"text-sm font-bold text-white leading-tight\">Receita Liberada</div>"
print "                   <div className=\"text-[10px] text-text-secondary mt-0.5\">Disponível para download</div>"
print "                </div>"
print "              </div>"
print "              <div className=\"p-8 pt-20 flex flex-col items-center h-full text-center relative bg-gradient-to-b from-[#111] to-[#050505]\">"
print "                <div className=\"w-24 h-24 bg-accent rounded-[2rem] flex items-center justify-center mb-8 shadow-[0_0_40px_rgba(204,255,0,0.2)]\">"
print "                  <Leaf className=\"w-12 h-12 text-black\" />"
print "                </div>"
print "                <h3 className=\"text-3xl font-display uppercase tracking-wide mb-3 text-white\">Mecura</h3>"
print "                <p className=\"text-text-secondary text-sm mb-10 px-4\">Da consulta à entrega, simples e seguro.</p>"
print "                <button className=\"w-full py-4 bg-accent text-black font-display tracking-widest uppercase rounded-full text-sm mb-10 hover:scale-105 transition-transform duration-300\">"
print "                  Obter App"
print "                </button>"
print "                <div className=\"flex items-center justify-center gap-4 border-y border-white/5 py-5 w-full mb-10\">"
print "                  <div className=\"text-center\">"
print "                    <div className=\"text-3xl font-display text-white mb-2\">4,9</div>"
print "                    <div className=\"flex text-accent gap-1.5 justify-center mb-1\">"
print "                      <Star className=\"w-3 h-3 fill-current\" />"
print "                      <Star className=\"w-3 h-3 fill-current\" />"
print "                      <Star className=\"w-3 h-3 fill-current\" />"
print "                      <Star className=\"w-3 h-3 fill-current\" />"
print "                      <Star className=\"w-3 h-3 fill-current\" />"
print "                    </div>"
print "                    <div className=\"text-[9px] text-text-muted uppercase tracking-widest font-bold\">2,4 mil avaliações</div>"
print "                  </div>"
print "                </div>"
print "                <div className=\"w-full bg-[#111] p-5 rounded-2xl text-left border border-white/5 relative overflow-hidden mt-auto\">"
print "                   <div className=\"absolute top-0 right-0 w-32 h-32 bg-accent/5 rounded-full blur-[30px] -translate-y-1/2 translate-x-1/2 pointer-events-none\"></div>"
print "                   <span className=\"text-accent text-[10px] font-bold uppercase tracking-[0.2em] mb-3 block\">Praticidade</span>"
print "                   <p className=\"text-xs text-text-secondary leading-relaxed\">"
print "                     Todo o seu tratamento unificado. Histórico, documentos e acompanhamento médico sem complicação."
print "                   </p>"
print "                </div>"
print "              </div>"
print "            </motion.div>"
print "        </div>"
print "      </div>"
print "    </section>"
print "  );"
print "}"
print ""
}
{ print }
' src/App.tsx > src/App.tmp && mv src/App.tmp src/App.tsx
